import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from '@/redux/providers';
import Navigation from '@/components/navigation';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Horizoon',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
    return (
        <html lang="en" className="dark" suppressHydrationWarning={true}>
            <head>
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
            </head>

            <body
                className={`${inter.className} bg-gradient-to-r from-white via-white to-white dark:bg-gradient-to-r dark:via-slate-950 dark:to-black dark:xs:from-slate-950 dark:sm:from-slate-900`}
            >
                <Providers>
                    <Navigation />
                    {children}
                    <Toaster />
                </Providers>
            </body>
        </html>
    );
};

export default RootLayout;
