import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from '@/redux/providers';
import Navigation from '@/components/navigation';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Horizoon',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
    return (
        <html lang="en" className="dark" suppressHydrationWarning>
            <head>
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
            </head>

            <body
                className={`${inter.className} bg-gradient-to-r from-slate-200 via-gray-100 to-white dark:bg-gradient-to-r dark:from-slate-900 dark:via-slate-900 dark:to-slate-950`}
            >
                <Providers>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <Navigation />
                        <div>{children}</div>
                    </ThemeProvider>
                </Providers>
            </body>
        </html>
    );
};

export default RootLayout;
